sudo: false
language: perl
perl:
   - '5.30'
   - '5.28'
   - '5.26'
   - '5.24'
   - 'blead'
dist: 'bionic'
matrix:
   allow_failures:
      - perl: 'blead'
   fast_finish: true
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet Perl::Tidy
   - cpanm --quiet --notest --skip-satisfied Dist::Zilla Pod::Weaver::Section::Support
   - "(cd Module-Format/Module-Format/ && dzil authordeps          --missing | grep -vP '[^\\w:]' | xargs -n 5 -P 10 cpanm --quiet --notest)"
   - "(cd Module-Format/Module-Format/ && dzil listdeps   --author --missing | grep -vP '[^\\w:]' | cpanm --verbose)"
script:
   - "cd Module-Format/Module-Format/ && dzil smoke --release --author"
